# conda env create -f environment.yml
name: xopt-dev
channels:
  - conda-forge
dependencies:
  - python=3.8
  - deap
  - numpy
  - pydantic
  - pyyaml
  - pandas
  - pyepics
  - ipywidgets
  - pytorch=1.7.1
  - botorch=0.4.0
  - gpytorch=1.4
  - tqdm
# parallel
  - mpi4py
  - dask
# Developer
  - pytest
  - jupyterlab>=3
  - matplotlib
  - pygments
  - numdifftools
  - pip
  - pip:
    - git+https://github.com/ChristopherMayes/Xopt.git@918a317
